#!/bin/bash

VENV="./env/"
DATA="./COVID-19-TweetIDs/"

if [ ! -d "$VENV" ]; then
    echo "venv for python3 not found, making a new one"
    echo ""
    python3 -m pip install --user virtualenv
    python3 -m venv env
else
    echo "venv already created"
fi

echo ""

if [ ! -d "$DATA" ]; then
    each "cloning hydrated data from github"
    git clone git@github.com:echen102/COVID-19-TweetIDs.git
else
    echo "dehydrated data found"
fi

echo ""

source env/bin/activate
which python

echo ""

pip install --upgrade pip
python -m pip install -r requirements.txt
